import { writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const OUT = resolve(__dirname, '../src/data/quran.ts')

const SURAH_IDS = [1, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114]
const TRANSLATION_ID = 20

const SAHEEH_MEANINGS = {
  1: 'The Opening',
  105: 'The Elephant',
  106: 'Quraysh',
  107: 'Small Kindnesses',
  108: 'Abundance',
  109: 'The Disbelievers',
  110: 'The Divine Support',
  111: 'The Palm Fiber',
  112: 'The Sincerity',
  113: 'The Daybreak',
  114: 'Mankind',
}

async function fetchChapter(id) {
  const res = await fetch(`https://api.quran.com/api/v4/chapters/${id}?language=en`)
  if (!res.ok) throw new Error(`chapters ${id}: ${res.status}`)
  const data = await res.json()
  return data.chapter
}

async function fetchVerses(id) {
  const url = `https://api.quran.com/api/v4/verses/by_chapter/${id}?translations=${TRANSLATION_ID}&fields=text_uthmani&per_page=300`
  const res = await fetch(url)
  if (!res.ok) throw new Error(`verses ${id}: ${res.status}`)
  const data = await res.json()
  return data.verses
}

function cleanTranslation(raw) {
  return raw
    .replace(/<sup[^>]*>.*?<\/sup>/g, '')
    .replace(/<[^>]+>/g, '')
    .replace(/\s+/g, ' ')
    .trim()
}

function normalizeArabic(raw) {
  return raw
    .replace(/\u200f/g, '')
    .replace(/\u200e/g, '')
    .replace(/\s+/g, ' ')
    .trim()
}

function tokenize(text) {
  return text
    .split(/\s+/)
    .filter(Boolean)
    .map((word, index) => ({ text: word, index }))
}

function toLiteral(value) {
  return JSON.stringify(value)
}

function emitSurah(surah) {
  const ayatLiteral = surah.ayat
    .map(
      (ayah) => `    {
      number: ${ayah.number},
      text: ${toLiteral(ayah.text)},
      translation: ${toLiteral(ayah.translation)},
      words: [
${ayah.words
  .map((w) => `        { index: ${w.index}, text: ${toLiteral(w.text)} },`)
  .join('\n')}
      ],
    }`,
    )
    .join(',\n')

  return `  {
    id: ${surah.id},
    nameSimple: ${toLiteral(surah.nameSimple)},
    nameComplex: ${toLiteral(surah.nameComplex)},
    nameArabic: ${toLiteral(surah.nameArabic)},
    meaning: ${toLiteral(surah.meaning)},
    revelationPlace: ${toLiteral(surah.revelationPlace)},
    revelationOrder: ${surah.revelationOrder},
    versesCount: ${surah.versesCount},
    bismillahPre: ${surah.bismillahPre},
    ayat: [
${ayatLiteral}
    ],
  }`
}

async function main() {
  const surahs = []

  for (const id of SURAH_IDS) {
    process.stdout.write(`• surah ${id}… `)
    const chapter = await fetchChapter(id)
    const verses = await fetchVerses(id)

    const ayat = verses.map((v) => {
      const text = normalizeArabic(v.text_uthmani)
      const translation = cleanTranslation(v.translations?.[0]?.text ?? '')
      return {
        number: v.verse_number,
        text,
        words: tokenize(text),
        translation,
      }
    })

    surahs.push({
      id,
      nameSimple: chapter.name_simple,
      nameComplex: chapter.name_complex,
      nameArabic: chapter.name_arabic,
      meaning: SAHEEH_MEANINGS[id] ?? chapter.translated_name?.name ?? '',
      revelationPlace: chapter.revelation_place,
      revelationOrder: chapter.revelation_order,
      versesCount: chapter.verses_count,
      bismillahPre: chapter.bismillah_pre,
      ayat,
    })

    process.stdout.write(`${ayat.length} ayat ✓\n`)
  }

  const header = `// Auto-generated by scripts/fetch-quran.mjs — do not edit by hand.
// Source: Quran.com API v4 (Tanzil Ḥafṣ ʿan ʿĀṣim Uthmani text, Saheeh International translation).
// Regenerate with: node scripts/fetch-quran.mjs

import type { Surah } from './types'

export const SURAHS: Surah[] = [
`

  const footer = `
]

export const SURAH_BY_ID = new Map(SURAHS.map((s) => [s.id, s]))
`

  const body = surahs.map(emitSurah).join(',\n')
  const file = header + body + footer

  await writeFile(OUT, file, 'utf8')
  console.log(`\nwrote ${OUT}`)
  console.log(`${surahs.length} surahs, ${surahs.reduce((n, s) => n + s.ayat.length, 0)} ayat`)
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
