// Auto-generated by scripts/fetch-quran.mjs — do not edit by hand.
// Source: Quran.com API v4 (Tanzil Ḥafṣ ʿan ʿĀṣim Uthmani text, Saheeh International translation).
// Regenerate with: node scripts/fetch-quran.mjs

import type { Surah } from './types'

export const SURAHS: Surah[] = [
  {
    id: 1,
    nameSimple: "Al-Fatihah",
    nameComplex: "Al-Fātiĥah",
    nameArabic: "الفاتحة",
    meaning: "The Opening",
    revelationPlace: "makkah",
    revelationOrder: 5,
    versesCount: 7,
    bismillahPre: false,
    ayat: [
    {
      number: 1,
      text: "بِسْمِ ٱللَّهِ ٱلرَّحْمَـٰنِ ٱلرَّحِيمِ",
      translation: "In the name of Allāh, the Entirely Merciful, the Especially Merciful.",
      words: [
        { index: 0, text: "بِسْمِ" },
        { index: 1, text: "ٱللَّهِ" },
        { index: 2, text: "ٱلرَّحْمَـٰنِ" },
        { index: 3, text: "ٱلرَّحِيمِ" },
      ],
    },
    {
      number: 2,
      text: "ٱلْحَمْدُ لِلَّهِ رَبِّ ٱلْعَـٰلَمِينَ",
      translation: "[All] praise is [due] to Allāh, Lord of the worlds -",
      words: [
        { index: 0, text: "ٱلْحَمْدُ" },
        { index: 1, text: "لِلَّهِ" },
        { index: 2, text: "رَبِّ" },
        { index: 3, text: "ٱلْعَـٰلَمِينَ" },
      ],
    },
    {
      number: 3,
      text: "ٱلرَّحْمَـٰنِ ٱلرَّحِيمِ",
      translation: "The Entirely Merciful, the Especially Merciful,",
      words: [
        { index: 0, text: "ٱلرَّحْمَـٰنِ" },
        { index: 1, text: "ٱلرَّحِيمِ" },
      ],
    },
    {
      number: 4,
      text: "مَـٰلِكِ يَوْمِ ٱلدِّينِ",
      translation: "Sovereign of the Day of Recompense.",
      words: [
        { index: 0, text: "مَـٰلِكِ" },
        { index: 1, text: "يَوْمِ" },
        { index: 2, text: "ٱلدِّينِ" },
      ],
    },
    {
      number: 5,
      text: "إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ",
      translation: "It is You we worship and You we ask for help.",
      words: [
        { index: 0, text: "إِيَّاكَ" },
        { index: 1, text: "نَعْبُدُ" },
        { index: 2, text: "وَإِيَّاكَ" },
        { index: 3, text: "نَسْتَعِينُ" },
      ],
    },
    {
      number: 6,
      text: "ٱهْدِنَا ٱلصِّرَٰطَ ٱلْمُسْتَقِيمَ",
      translation: "Guide us to the straight path -",
      words: [
        { index: 0, text: "ٱهْدِنَا" },
        { index: 1, text: "ٱلصِّرَٰطَ" },
        { index: 2, text: "ٱلْمُسْتَقِيمَ" },
      ],
    },
    {
      number: 7,
      text: "صِرَٰطَ ٱلَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ ٱلْمَغْضُوبِ عَلَيْهِمْ وَلَا ٱلضَّآلِّينَ",
      translation: "The path of those upon whom You have bestowed favor, not of those who have earned [Your] anger or of those who are astray.",
      words: [
        { index: 0, text: "صِرَٰطَ" },
        { index: 1, text: "ٱلَّذِينَ" },
        { index: 2, text: "أَنْعَمْتَ" },
        { index: 3, text: "عَلَيْهِمْ" },
        { index: 4, text: "غَيْرِ" },
        { index: 5, text: "ٱلْمَغْضُوبِ" },
        { index: 6, text: "عَلَيْهِمْ" },
        { index: 7, text: "وَلَا" },
        { index: 8, text: "ٱلضَّآلِّينَ" },
      ],
    }
    ],
  },
  {
    id: 105,
    nameSimple: "Al-Fil",
    nameComplex: "Al-Fīl",
    nameArabic: "الفيل",
    meaning: "The Elephant",
    revelationPlace: "makkah",
    revelationOrder: 19,
    versesCount: 5,
    bismillahPre: true,
    ayat: [
    {
      number: 1,
      text: "أَلَمْ تَرَ كَيْفَ فَعَلَ رَبُّكَ بِأَصْحَـٰبِ ٱلْفِيلِ",
      translation: "Have you not considered, [O Muḥammad], how your Lord dealt with the companions of the elephant?",
      words: [
        { index: 0, text: "أَلَمْ" },
        { index: 1, text: "تَرَ" },
        { index: 2, text: "كَيْفَ" },
        { index: 3, text: "فَعَلَ" },
        { index: 4, text: "رَبُّكَ" },
        { index: 5, text: "بِأَصْحَـٰبِ" },
        { index: 6, text: "ٱلْفِيلِ" },
      ],
    },
    {
      number: 2,
      text: "أَلَمْ يَجْعَلْ كَيْدَهُمْ فِى تَضْلِيلٍ",
      translation: "Did He not make their plan into misguidance?",
      words: [
        { index: 0, text: "أَلَمْ" },
        { index: 1, text: "يَجْعَلْ" },
        { index: 2, text: "كَيْدَهُمْ" },
        { index: 3, text: "فِى" },
        { index: 4, text: "تَضْلِيلٍ" },
      ],
    },
    {
      number: 3,
      text: "وَأَرْسَلَ عَلَيْهِمْ طَيْرًا أَبَابِيلَ",
      translation: "And He sent against them birds in flocks,",
      words: [
        { index: 0, text: "وَأَرْسَلَ" },
        { index: 1, text: "عَلَيْهِمْ" },
        { index: 2, text: "طَيْرًا" },
        { index: 3, text: "أَبَابِيلَ" },
      ],
    },
    {
      number: 4,
      text: "تَرْمِيهِم بِحِجَارَةٍ مِّن سِجِّيلٍ",
      translation: "Striking them with stones of hard clay,",
      words: [
        { index: 0, text: "تَرْمِيهِم" },
        { index: 1, text: "بِحِجَارَةٍ" },
        { index: 2, text: "مِّن" },
        { index: 3, text: "سِجِّيلٍ" },
      ],
    },
    {
      number: 5,
      text: "فَجَعَلَهُمْ كَعَصْفٍ مَّأْكُولٍۭ",
      translation: "And He made them like eaten straw.",
      words: [
        { index: 0, text: "فَجَعَلَهُمْ" },
        { index: 1, text: "كَعَصْفٍ" },
        { index: 2, text: "مَّأْكُولٍۭ" },
      ],
    }
    ],
  },
  {
    id: 106,
    nameSimple: "Quraysh",
    nameComplex: "Quraysh",
    nameArabic: "قريش",
    meaning: "Quraysh",
    revelationPlace: "makkah",
    revelationOrder: 29,
    versesCount: 4,
    bismillahPre: true,
    ayat: [
    {
      number: 1,
      text: "لِإِيلَـٰفِ قُرَيْشٍ",
      translation: "For the accustomed security of the Quraysh -",
      words: [
        { index: 0, text: "لِإِيلَـٰفِ" },
        { index: 1, text: "قُرَيْشٍ" },
      ],
    },
    {
      number: 2,
      text: "إِۦلَـٰفِهِمْ رِحْلَةَ ٱلشِّتَآءِ وَٱلصَّيْفِ",
      translation: "Their accustomed security [in] the caravan of winter and summer -",
      words: [
        { index: 0, text: "إِۦلَـٰفِهِمْ" },
        { index: 1, text: "رِحْلَةَ" },
        { index: 2, text: "ٱلشِّتَآءِ" },
        { index: 3, text: "وَٱلصَّيْفِ" },
      ],
    },
    {
      number: 3,
      text: "فَلْيَعْبُدُوا۟ رَبَّ هَـٰذَا ٱلْبَيْتِ",
      translation: "Let them worship the Lord of this House,",
      words: [
        { index: 0, text: "فَلْيَعْبُدُوا۟" },
        { index: 1, text: "رَبَّ" },
        { index: 2, text: "هَـٰذَا" },
        { index: 3, text: "ٱلْبَيْتِ" },
      ],
    },
    {
      number: 4,
      text: "ٱلَّذِىٓ أَطْعَمَهُم مِّن جُوعٍ وَءَامَنَهُم مِّنْ خَوْفٍۭ",
      translation: "Who has fed them, [saving them] from hunger and made them safe, [saving them] from fear.",
      words: [
        { index: 0, text: "ٱلَّذِىٓ" },
        { index: 1, text: "أَطْعَمَهُم" },
        { index: 2, text: "مِّن" },
        { index: 3, text: "جُوعٍ" },
        { index: 4, text: "وَءَامَنَهُم" },
        { index: 5, text: "مِّنْ" },
        { index: 6, text: "خَوْفٍۭ" },
      ],
    }
    ],
  },
  {
    id: 107,
    nameSimple: "Al-Ma'un",
    nameComplex: "Al-Mā`ūn",
    nameArabic: "الماعون",
    meaning: "Small Kindnesses",
    revelationPlace: "makkah",
    revelationOrder: 17,
    versesCount: 7,
    bismillahPre: true,
    ayat: [
    {
      number: 1,
      text: "أَرَءَيْتَ ٱلَّذِى يُكَذِّبُ بِٱلدِّينِ",
      translation: "Have you seen the one who denies the Recompense?",
      words: [
        { index: 0, text: "أَرَءَيْتَ" },
        { index: 1, text: "ٱلَّذِى" },
        { index: 2, text: "يُكَذِّبُ" },
        { index: 3, text: "بِٱلدِّينِ" },
      ],
    },
    {
      number: 2,
      text: "فَذَٰلِكَ ٱلَّذِى يَدُعُّ ٱلْيَتِيمَ",
      translation: "For that is the one who drives away the orphan",
      words: [
        { index: 0, text: "فَذَٰلِكَ" },
        { index: 1, text: "ٱلَّذِى" },
        { index: 2, text: "يَدُعُّ" },
        { index: 3, text: "ٱلْيَتِيمَ" },
      ],
    },
    {
      number: 3,
      text: "وَلَا يَحُضُّ عَلَىٰ طَعَامِ ٱلْمِسْكِينِ",
      translation: "And does not encourage the feeding of the poor.",
      words: [
        { index: 0, text: "وَلَا" },
        { index: 1, text: "يَحُضُّ" },
        { index: 2, text: "عَلَىٰ" },
        { index: 3, text: "طَعَامِ" },
        { index: 4, text: "ٱلْمِسْكِينِ" },
      ],
    },
    {
      number: 4,
      text: "فَوَيْلٌ لِّلْمُصَلِّينَ",
      translation: "So woe to those who pray",
      words: [
        { index: 0, text: "فَوَيْلٌ" },
        { index: 1, text: "لِّلْمُصَلِّينَ" },
      ],
    },
    {
      number: 5,
      text: "ٱلَّذِينَ هُمْ عَن صَلَاتِهِمْ سَاهُونَ",
      translation: "[But] who are heedless of their prayer -",
      words: [
        { index: 0, text: "ٱلَّذِينَ" },
        { index: 1, text: "هُمْ" },
        { index: 2, text: "عَن" },
        { index: 3, text: "صَلَاتِهِمْ" },
        { index: 4, text: "سَاهُونَ" },
      ],
    },
    {
      number: 6,
      text: "ٱلَّذِينَ هُمْ يُرَآءُونَ",
      translation: "Those who make show [of their deeds]",
      words: [
        { index: 0, text: "ٱلَّذِينَ" },
        { index: 1, text: "هُمْ" },
        { index: 2, text: "يُرَآءُونَ" },
      ],
    },
    {
      number: 7,
      text: "وَيَمْنَعُونَ ٱلْمَاعُونَ",
      translation: "And withhold [simple] assistance.",
      words: [
        { index: 0, text: "وَيَمْنَعُونَ" },
        { index: 1, text: "ٱلْمَاعُونَ" },
      ],
    }
    ],
  },
  {
    id: 108,
    nameSimple: "Al-Kawthar",
    nameComplex: "Al-Kawthar",
    nameArabic: "الكوثر",
    meaning: "Abundance",
    revelationPlace: "makkah",
    revelationOrder: 15,
    versesCount: 3,
    bismillahPre: true,
    ayat: [
    {
      number: 1,
      text: "إِنَّآ أَعْطَيْنَـٰكَ ٱلْكَوْثَرَ",
      translation: "Indeed, We have granted you, [O Muḥammad], al-Kawthar.",
      words: [
        { index: 0, text: "إِنَّآ" },
        { index: 1, text: "أَعْطَيْنَـٰكَ" },
        { index: 2, text: "ٱلْكَوْثَرَ" },
      ],
    },
    {
      number: 2,
      text: "فَصَلِّ لِرَبِّكَ وَٱنْحَرْ",
      translation: "So pray to your Lord and offer sacrifice [to Him alone].",
      words: [
        { index: 0, text: "فَصَلِّ" },
        { index: 1, text: "لِرَبِّكَ" },
        { index: 2, text: "وَٱنْحَرْ" },
      ],
    },
    {
      number: 3,
      text: "إِنَّ شَانِئَكَ هُوَ ٱلْأَبْتَرُ",
      translation: "Indeed, your enemy is the one cut off.",
      words: [
        { index: 0, text: "إِنَّ" },
        { index: 1, text: "شَانِئَكَ" },
        { index: 2, text: "هُوَ" },
        { index: 3, text: "ٱلْأَبْتَرُ" },
      ],
    }
    ],
  },
  {
    id: 109,
    nameSimple: "Al-Kafirun",
    nameComplex: "Al-Kāfirūn",
    nameArabic: "الكافرون",
    meaning: "The Disbelievers",
    revelationPlace: "makkah",
    revelationOrder: 18,
    versesCount: 6,
    bismillahPre: true,
    ayat: [
    {
      number: 1,
      text: "قُلْ يَـٰٓأَيُّهَا ٱلْكَـٰفِرُونَ",
      translation: "Say, \"O disbelievers,",
      words: [
        { index: 0, text: "قُلْ" },
        { index: 1, text: "يَـٰٓأَيُّهَا" },
        { index: 2, text: "ٱلْكَـٰفِرُونَ" },
      ],
    },
    {
      number: 2,
      text: "لَآ أَعْبُدُ مَا تَعْبُدُونَ",
      translation: "I do not worship what you worship.",
      words: [
        { index: 0, text: "لَآ" },
        { index: 1, text: "أَعْبُدُ" },
        { index: 2, text: "مَا" },
        { index: 3, text: "تَعْبُدُونَ" },
      ],
    },
    {
      number: 3,
      text: "وَلَآ أَنتُمْ عَـٰبِدُونَ مَآ أَعْبُدُ",
      translation: "Nor are you worshippers of what I worship.",
      words: [
        { index: 0, text: "وَلَآ" },
        { index: 1, text: "أَنتُمْ" },
        { index: 2, text: "عَـٰبِدُونَ" },
        { index: 3, text: "مَآ" },
        { index: 4, text: "أَعْبُدُ" },
      ],
    },
    {
      number: 4,
      text: "وَلَآ أَنَا۠ عَابِدٌ مَّا عَبَدتُّمْ",
      translation: "Nor will I be a worshipper of what you worship.",
      words: [
        { index: 0, text: "وَلَآ" },
        { index: 1, text: "أَنَا۠" },
        { index: 2, text: "عَابِدٌ" },
        { index: 3, text: "مَّا" },
        { index: 4, text: "عَبَدتُّمْ" },
      ],
    },
    {
      number: 5,
      text: "وَلَآ أَنتُمْ عَـٰبِدُونَ مَآ أَعْبُدُ",
      translation: "Nor will you be worshippers of what I worship.",
      words: [
        { index: 0, text: "وَلَآ" },
        { index: 1, text: "أَنتُمْ" },
        { index: 2, text: "عَـٰبِدُونَ" },
        { index: 3, text: "مَآ" },
        { index: 4, text: "أَعْبُدُ" },
      ],
    },
    {
      number: 6,
      text: "لَكُمْ دِينُكُمْ وَلِىَ دِينِ",
      translation: "For you is your religion, and for me is my religion.\"",
      words: [
        { index: 0, text: "لَكُمْ" },
        { index: 1, text: "دِينُكُمْ" },
        { index: 2, text: "وَلِىَ" },
        { index: 3, text: "دِينِ" },
      ],
    }
    ],
  },
  {
    id: 110,
    nameSimple: "An-Nasr",
    nameComplex: "An-Naşr",
    nameArabic: "النصر",
    meaning: "The Divine Support",
    revelationPlace: "madinah",
    revelationOrder: 114,
    versesCount: 3,
    bismillahPre: true,
    ayat: [
    {
      number: 1,
      text: "إِذَا جَآءَ نَصْرُ ٱللَّهِ وَٱلْفَتْحُ",
      translation: "When the victory of Allāh has come and the conquest,",
      words: [
        { index: 0, text: "إِذَا" },
        { index: 1, text: "جَآءَ" },
        { index: 2, text: "نَصْرُ" },
        { index: 3, text: "ٱللَّهِ" },
        { index: 4, text: "وَٱلْفَتْحُ" },
      ],
    },
    {
      number: 2,
      text: "وَرَأَيْتَ ٱلنَّاسَ يَدْخُلُونَ فِى دِينِ ٱللَّهِ أَفْوَاجًا",
      translation: "And you see the people entering into the religion of Allāh in multitudes,",
      words: [
        { index: 0, text: "وَرَأَيْتَ" },
        { index: 1, text: "ٱلنَّاسَ" },
        { index: 2, text: "يَدْخُلُونَ" },
        { index: 3, text: "فِى" },
        { index: 4, text: "دِينِ" },
        { index: 5, text: "ٱللَّهِ" },
        { index: 6, text: "أَفْوَاجًا" },
      ],
    },
    {
      number: 3,
      text: "فَسَبِّحْ بِحَمْدِ رَبِّكَ وَٱسْتَغْفِرْهُ ۚ إِنَّهُۥ كَانَ تَوَّابًۢا",
      translation: "Then exalt [Him] with praise of your Lord and ask forgiveness of Him. Indeed, He is ever Accepting of Repentance.",
      words: [
        { index: 0, text: "فَسَبِّحْ" },
        { index: 1, text: "بِحَمْدِ" },
        { index: 2, text: "رَبِّكَ" },
        { index: 3, text: "وَٱسْتَغْفِرْهُ" },
        { index: 4, text: "ۚ" },
        { index: 5, text: "إِنَّهُۥ" },
        { index: 6, text: "كَانَ" },
        { index: 7, text: "تَوَّابًۢا" },
      ],
    }
    ],
  },
  {
    id: 111,
    nameSimple: "Al-Masad",
    nameComplex: "Al-Masad",
    nameArabic: "المسد",
    meaning: "The Palm Fiber",
    revelationPlace: "makkah",
    revelationOrder: 6,
    versesCount: 5,
    bismillahPre: true,
    ayat: [
    {
      number: 1,
      text: "تَبَّتْ يَدَآ أَبِى لَهَبٍ وَتَبَّ",
      translation: "May the hands of Abū Lahab be ruined, and ruined is he.",
      words: [
        { index: 0, text: "تَبَّتْ" },
        { index: 1, text: "يَدَآ" },
        { index: 2, text: "أَبِى" },
        { index: 3, text: "لَهَبٍ" },
        { index: 4, text: "وَتَبَّ" },
      ],
    },
    {
      number: 2,
      text: "مَآ أَغْنَىٰ عَنْهُ مَالُهُۥ وَمَا كَسَبَ",
      translation: "His wealth will not avail him or that which he gained.",
      words: [
        { index: 0, text: "مَآ" },
        { index: 1, text: "أَغْنَىٰ" },
        { index: 2, text: "عَنْهُ" },
        { index: 3, text: "مَالُهُۥ" },
        { index: 4, text: "وَمَا" },
        { index: 5, text: "كَسَبَ" },
      ],
    },
    {
      number: 3,
      text: "سَيَصْلَىٰ نَارًا ذَاتَ لَهَبٍ",
      translation: "He will [enter to] burn in a Fire of [blazing] flame",
      words: [
        { index: 0, text: "سَيَصْلَىٰ" },
        { index: 1, text: "نَارًا" },
        { index: 2, text: "ذَاتَ" },
        { index: 3, text: "لَهَبٍ" },
      ],
    },
    {
      number: 4,
      text: "وَٱمْرَأَتُهُۥ حَمَّالَةَ ٱلْحَطَبِ",
      translation: "And his wife [as well] - the carrier of firewood.",
      words: [
        { index: 0, text: "وَٱمْرَأَتُهُۥ" },
        { index: 1, text: "حَمَّالَةَ" },
        { index: 2, text: "ٱلْحَطَبِ" },
      ],
    },
    {
      number: 5,
      text: "فِى جِيدِهَا حَبْلٌ مِّن مَّسَدٍۭ",
      translation: "Around her neck is a rope of [twisted] fiber.",
      words: [
        { index: 0, text: "فِى" },
        { index: 1, text: "جِيدِهَا" },
        { index: 2, text: "حَبْلٌ" },
        { index: 3, text: "مِّن" },
        { index: 4, text: "مَّسَدٍۭ" },
      ],
    }
    ],
  },
  {
    id: 112,
    nameSimple: "Al-Ikhlas",
    nameComplex: "Al-'Ikhlāş",
    nameArabic: "الإخلاص",
    meaning: "The Sincerity",
    revelationPlace: "makkah",
    revelationOrder: 22,
    versesCount: 4,
    bismillahPre: true,
    ayat: [
    {
      number: 1,
      text: "قُلْ هُوَ ٱللَّهُ أَحَدٌ",
      translation: "Say, \"He is Allāh, [who is] One,",
      words: [
        { index: 0, text: "قُلْ" },
        { index: 1, text: "هُوَ" },
        { index: 2, text: "ٱللَّهُ" },
        { index: 3, text: "أَحَدٌ" },
      ],
    },
    {
      number: 2,
      text: "ٱللَّهُ ٱلصَّمَدُ",
      translation: "Allāh, the Eternal Refuge.",
      words: [
        { index: 0, text: "ٱللَّهُ" },
        { index: 1, text: "ٱلصَّمَدُ" },
      ],
    },
    {
      number: 3,
      text: "لَمْ يَلِدْ وَلَمْ يُولَدْ",
      translation: "He neither begets nor is born,",
      words: [
        { index: 0, text: "لَمْ" },
        { index: 1, text: "يَلِدْ" },
        { index: 2, text: "وَلَمْ" },
        { index: 3, text: "يُولَدْ" },
      ],
    },
    {
      number: 4,
      text: "وَلَمْ يَكُن لَّهُۥ كُفُوًا أَحَدٌۢ",
      translation: "Nor is there to Him any equivalent.\"",
      words: [
        { index: 0, text: "وَلَمْ" },
        { index: 1, text: "يَكُن" },
        { index: 2, text: "لَّهُۥ" },
        { index: 3, text: "كُفُوًا" },
        { index: 4, text: "أَحَدٌۢ" },
      ],
    }
    ],
  },
  {
    id: 113,
    nameSimple: "Al-Falaq",
    nameComplex: "Al-Falaq",
    nameArabic: "الفلق",
    meaning: "The Daybreak",
    revelationPlace: "makkah",
    revelationOrder: 20,
    versesCount: 5,
    bismillahPre: true,
    ayat: [
    {
      number: 1,
      text: "قُلْ أَعُوذُ بِرَبِّ ٱلْفَلَقِ",
      translation: "Say, \"I seek refuge in the Lord of daybreak",
      words: [
        { index: 0, text: "قُلْ" },
        { index: 1, text: "أَعُوذُ" },
        { index: 2, text: "بِرَبِّ" },
        { index: 3, text: "ٱلْفَلَقِ" },
      ],
    },
    {
      number: 2,
      text: "مِن شَرِّ مَا خَلَقَ",
      translation: "From the evil of that which He created",
      words: [
        { index: 0, text: "مِن" },
        { index: 1, text: "شَرِّ" },
        { index: 2, text: "مَا" },
        { index: 3, text: "خَلَقَ" },
      ],
    },
    {
      number: 3,
      text: "وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ",
      translation: "And from the evil of darkness when it settles",
      words: [
        { index: 0, text: "وَمِن" },
        { index: 1, text: "شَرِّ" },
        { index: 2, text: "غَاسِقٍ" },
        { index: 3, text: "إِذَا" },
        { index: 4, text: "وَقَبَ" },
      ],
    },
    {
      number: 4,
      text: "وَمِن شَرِّ ٱلنَّفَّـٰثَـٰتِ فِى ٱلْعُقَدِ",
      translation: "And from the evil of the blowers in knots",
      words: [
        { index: 0, text: "وَمِن" },
        { index: 1, text: "شَرِّ" },
        { index: 2, text: "ٱلنَّفَّـٰثَـٰتِ" },
        { index: 3, text: "فِى" },
        { index: 4, text: "ٱلْعُقَدِ" },
      ],
    },
    {
      number: 5,
      text: "وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ",
      translation: "And from the evil of an envier when he envies.\"",
      words: [
        { index: 0, text: "وَمِن" },
        { index: 1, text: "شَرِّ" },
        { index: 2, text: "حَاسِدٍ" },
        { index: 3, text: "إِذَا" },
        { index: 4, text: "حَسَدَ" },
      ],
    }
    ],
  },
  {
    id: 114,
    nameSimple: "An-Nas",
    nameComplex: "An-Nās",
    nameArabic: "الناس",
    meaning: "Mankind",
    revelationPlace: "makkah",
    revelationOrder: 21,
    versesCount: 6,
    bismillahPre: true,
    ayat: [
    {
      number: 1,
      text: "قُلْ أَعُوذُ بِرَبِّ ٱلنَّاسِ",
      translation: "Say, \"I seek refuge in the Lord of mankind,",
      words: [
        { index: 0, text: "قُلْ" },
        { index: 1, text: "أَعُوذُ" },
        { index: 2, text: "بِرَبِّ" },
        { index: 3, text: "ٱلنَّاسِ" },
      ],
    },
    {
      number: 2,
      text: "مَلِكِ ٱلنَّاسِ",
      translation: "The Sovereign of mankind,",
      words: [
        { index: 0, text: "مَلِكِ" },
        { index: 1, text: "ٱلنَّاسِ" },
      ],
    },
    {
      number: 3,
      text: "إِلَـٰهِ ٱلنَّاسِ",
      translation: "The God of mankind,",
      words: [
        { index: 0, text: "إِلَـٰهِ" },
        { index: 1, text: "ٱلنَّاسِ" },
      ],
    },
    {
      number: 4,
      text: "مِن شَرِّ ٱلْوَسْوَاسِ ٱلْخَنَّاسِ",
      translation: "From the evil of the retreating whisperer -",
      words: [
        { index: 0, text: "مِن" },
        { index: 1, text: "شَرِّ" },
        { index: 2, text: "ٱلْوَسْوَاسِ" },
        { index: 3, text: "ٱلْخَنَّاسِ" },
      ],
    },
    {
      number: 5,
      text: "ٱلَّذِى يُوَسْوِسُ فِى صُدُورِ ٱلنَّاسِ",
      translation: "Who whispers [evil] into the breasts of mankind -",
      words: [
        { index: 0, text: "ٱلَّذِى" },
        { index: 1, text: "يُوَسْوِسُ" },
        { index: 2, text: "فِى" },
        { index: 3, text: "صُدُورِ" },
        { index: 4, text: "ٱلنَّاسِ" },
      ],
    },
    {
      number: 6,
      text: "مِنَ ٱلْجِنَّةِ وَٱلنَّاسِ",
      translation: "From among the jinn and mankind\".",
      words: [
        { index: 0, text: "مِنَ" },
        { index: 1, text: "ٱلْجِنَّةِ" },
        { index: 2, text: "وَٱلنَّاسِ" },
      ],
    }
    ],
  }
]

export const SURAH_BY_ID = new Map(SURAHS.map((s) => [s.id, s]))
